### PR TITLE
[BUG-FIX] "Recent Searches" list doesn't work because of changed result list structure

### LINKED ISSUE #54: Recent Searches Not Working
Recent searches section seems to be broken as it is not showing previous searches.

### PR DESCRIPTION
**Pull request by icyflame**
## Bug

1. Clicking on a result link doesn't add the current search term to the recent searches link
1. Even if new searches are added, old searches are not removed properly leading to duplicates in the Recent Searches list (even though there are none in Local Storage)

## Trigger

#52 made a lot of changes to the UI and the JS code.

1. Recent searches not working
    1. Document click handler added the search to the recent searches list
    1. This handler was checking to see if the clicked element had the class `result-link`
    1. The result list structure was changed from `a.result-link` to `a.result-link > div h1`
    1. In the new structure, every click's target would be one of the children: `div` or `h1`, and neither of them have the `result-link` class, so the click handler would not consider the clicked element as a result link and won't add the search term to the recent searches list
1. Duplicate searches not removed from the Recent searches list
    1. Once bug 1 is fixed, this bug shows up. This was also introduced by the same PR
    1. When a new search term is clicked, the current logic performs the following steps:
        1. Replace current term it in the old stored string
        1. Add current term to the old string
        1. Store the string in `localStorage`
        1. Remove the elements matching the current term from the currently displayed Recent Searches list => BUG
        1. Prepend the current search term to the recent searches list (thus bringing to the top)
    1. In step 4 above, the removal relies on the structure of the Recent Searches list.
        1. Before: `ul.local-storage-list div > a`
        1. After: `ul.local-storage-list > li > a`

## Impact

- Recent searches were not stored for users since Oct 19, 2019

## Fix

1. Attach the handler to `a.result-link` => This ensures that the handler is triggered whenever the `a` or one of it's children are clicked
1. Fix the element pattern for removing duplicates from the recent searches page

I have tested this locally in a bunch of scenarios and it works as expected. :+1:  

Fix #54 

## Other changes in this PR

- #52 also converted several function calls to write the arguments one line each. This is especially confusing when the full search call can be accomodated on a single line. I changed some fuctions. I will run `semistandard --lint` on the JS file in a later PR.

### CODE REVIEW

File: client.js [hunk 1]
```diff
@@ -111,16 +94,20 @@ $(function() {
         '</h1></a><li>';
     }
     $('.result-list').html(html);
-    $('.result-link').click(function() {
-      ga(
```
Comment (icyflame) [inline client.js:115]: Argument per line function calls are confusing and shouldn't be used as long as the full function call can be fit in a single line with a width of 80-100 characters.

File: .editorconfig [hunk 2]
```diff
@@ -3,3 +3,7 @@ root = true
 [*.rb]
 indent_style = space
 indent_size = 2
+
+[*.js]
+indent_style = space
+indent_size = 2
```
Comment (thealphadollar) [inline .editorconfig:9]: I don't think this is required in the file tree and should be added to the `.gitignore`

File: client.js (hunk 1 above)
Comment (thealphadollar) [reply client.js:115]: Makes a lot of sense to me, we need to have sanitization practices.

**Review by thealphadollar — CHANGES_REQUESTED** [review]
LGTM. Thanks a lot for taking out time from your schedule to send the fix :sparkles: 

A small change I've requested, please see if it fits. I'll merge it post your response.

File: .editorconfig (hunk 2 above)
Comment (thealphadollar) [reply .editorconfig:9]: I fixed this myself.

Comment (icyflame) [reply .editorconfig:9]: @thealphadollar No, this _is_ required. `.editorconfig` ensures that everyone follows the same indenting. I will remove it from `.gitignore` and add it back in another PR.
